Controldeaplicaciones-TODOLIST/Controllers/APIController.cs
using Controldeaplicaciones_TODOLIST.Models;
using Controldeaplicaciones_TODOLIST.ServiceReferenceTask;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Controldeaplicaciones_TODOLIST.Controllers
{
    public class APIController : Controller
    {
        // GET: API
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> Listtask()
        {
            //https://localhost:44346/api/WebApiTask
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync("https://localhost:44346/api/WebApiTask");
            //Devuelve la vista del index ); 
            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
}

Controldeaplicaciones-TODOLIST/Controllers/WCFController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ServiceModel;
using Controldeaplicaciones_TODOLIST.Models;
using Controldeaplicaciones_TODOLIST.ServiceReferenceTask;
using Task = Controldeaplicaciones_TODOLIST.ServiceReferenceTask.Task;

namespace Controldeaplicaciones_TODOLIST.Controllers 
{
    public class WCFController : Controller 
    {
        // GET: WCF
        public ActionResult Index()
        {
            //Devuelve la vista del index 
            return View();
        }

        public JsonResult Listtask()
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            var list = srt.GetTasks();
            //Devuelve la vista del index 
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ListPrioridad(string filtro)
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            var list = srt.ListPriority(filtro);
            //Devuelve la vista del index 
            return Json(list, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetDatos(int id)
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            var list = srt.ListId(id);
            //Devuelve la vista del index 
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult InsertTask(Task itask)
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            srt.InsertTask(itask);
            return Json(itask);
        }

        public JsonResult EditTask(Task itask)
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            srt.EditTask(itask);
            return Json(itask);
        }

        public JsonResult ChangeStatusTask(int id)
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            srt.ChangeStatusTask(id);
            return Json(id);
        }

        public JsonResult DeleteTask(int id)
        {
            ServiceReferenceTask.TaskClient srt = new ConectionWcf().Conectar();
            srt.DeleteTask(id);
            return Json(id);
        }
    }
}

Controldeaplicaciones-TODOLIST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bootcamp Tismart</title>

    <!--Boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!--Icon Fontawesome-->
    <script src="https://kit.fontawesome.com/bfa4b5579c.js" crossorigin="anonymous"></script>
    <!--Jquery-->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <!--Sweet Alert-->
    <script src="~/Content/sweetalert2.all.js"></script>
    <!--Datetime-->
    <script src="~/Content/Datetime.js"></script>
    <!--Script-->
    <!--<script src="~/Content/main.js"></script>-->
    <!--<script src="~/Content/data.js"></script>-->
    <!--Moment.js-->
    <script src="~/Content/moment.js"></script>
    <!--DataTables-->
    <link href="~/Content/datatables.css" rel="stylesheet" />
</head>

<body>
    <style>
        a:link {
            text-decoration: none;
            color: white;
            margin: 25px;
        }
    </style>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid" >
            <div class="container">
                <h1 class="navbar-brand">@Html.ActionLink("𝐓𝐀𝐑𝐄𝐀𝐒 - 𝐒𝐐𝐋𝐒𝐄𝐑𝐕𝐄𝐑", "Index", "Home")</h1>
            </div>
            <div class="container">
                <h1 class="navbar-brand">@Html.ActionLink("𝐓𝐀𝐑𝐄𝐀𝐒 - 𝐖𝐂𝐅", "Index", "WCF")</h1>
            </div>
            <div class="container">
                <h1 class="navbar-brand">@Html.ActionLink("𝐓𝐀𝐑𝐄𝐀𝐒 - 𝐖𝐄𝐁 𝐀𝐏𝐈", "Index", "API")</h1>
            </div>
            @*<div class="container">
                <h1 class="navbar-brand">@Html.ActionLink("𝐓𝐀𝐑𝐄𝐀𝐒 - 𝐌𝐄𝐌𝐎𝐑𝐈𝐀", "Index", "WCF")</h1>
            </div>*@
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center">&copy; @DateTime.Now.Year - Retos Bootcamp Tismart</p>
        </footer>
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="~/Content/datatables.min.js"></script>
</body>
</html>